apiVersion: v2
name: platform-ingress
description: Platform ingress bundle (external, internal, infra) for AKS clusters
type: application

version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: GabrielHM
    email: gabriel@example.com

keywords:
  - kubernetes
  - ingress
  - platform
  - aks
  - gitops

home: https://github.com/GabrielHM98/cloud-engineering
sources:
  - https://github.com/GabrielHM98/cloud-engineering/aks  