apiVersion: v2
name: observability-stack
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "81.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: thanos
    version: "17.3.1"
    repository: "https://charts.bitnami.com/bitnami"
  - name: grafana
    version: "10.5.15"
    repository: "https://grafana.github.io/helm-charts"